version: '3.5'

services:
    demo-tornado: 
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:8080"
        # volumes:
        #     - .:/usr/src/app
        restart: always
        depends_on:
            - db
    db:
        image: "postgres"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./db/initdb.d:/docker-entrypoint-initdb.d
            - ./db/pgdata:/var/lib/postgresql/data