version: '3.3'

services:
    demo-tornado: 
        build: .
        ports:
            - "8000:8080"
        volumes:
            - .:/usr/src/app
        restart: always
        depends_on:
            - db
    db:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./db/initdb.d:/docker-entrypoint-initdb.d
            - ./data/pgdata:/var/lib/postgresql/data